apiVersion: v1
kind: Pod
metadata:
  name: django-todo-app
  namespace: django-todo-ns
spec:
  containers:
  - name: django-todo
    image: muskanpareek/django-todo-app:latest
    ports:
    - containerPort: 8000

